FROM node:22.23.2-alpine@sha256:b6f26b36c8ff49624cfdac716b8ea1138d606df02586a77d364bb5536a634f85

WORKDIR /app

ENV NODE_ENV=development

COPY --chown=node:node package.json package-lock.json ./
RUN npm ci

COPY --chown=node:node tsconfig.json tsconfig.test.json drizzle.config.ts ./
COPY --chown=node:node drizzle ./drizzle
COPY --chown=node:node src ./src
COPY --chown=node:node test ./test

USER node

EXPOSE 3000

CMD ["npm", "run", "dev"]
